# Generated by Django 5.0.1 on 2024-04-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('operacion', models.CharField(choices=[('Create', 'Create'), ('Read', 'Read'), ('Update', 'Update'), ('Delete', 'Delete')], default='Create', max_length=20)),
                ('tabla', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('restricciones', models.TextField()),
                ('estatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dietas',
            },
        ),
        migrations.CreateModel(
            name='indicadores_nutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('IMC', models.DecimalField(decimal_places=3, max_digits=5)),
                ('circunferencia_cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_nutriente_sangre', models.TextField()),
            ],
            options={
                'db_table': 'indicadores_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='membresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Familiar', 'Familiar'), ('Empresarial', 'Empresarial')], default='Individual', max_length=20)),
                ('tipo_servicios', models.CharField(choices=[('Basicos', 'Basicos'), ('Completa', 'Completa'), ('Coaching', 'Coaching'), ('Nutriólogo', 'Nutriólogo')], default='Basicos', max_length=20)),
                ('tipo_plan', models.CharField(choices=[('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Trimestral', 'Trimestral'), ('Bimestral', 'Bimestral'), ('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Diaria', 'Diaria')], default='Anual', max_length=20)),
                ('nivel', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Diamante', 'Diamante')], default='Nuevo', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membresias',
            },
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cortecia', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateTimeField(auto_now=True)),
                ('fotografia', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('No Binario', 'N/B')], default='Masculino', max_length=20)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=10)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='tbl_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_nombre', models.CharField(max_length=50)),
                ('d_apellidoPaterno', models.CharField(max_length=50)),
                ('d_apellidoMaterno', models.CharField(max_length=50)),
                ('d_direccion', models.CharField(max_length=150)),
                ('d_telefono', models.CharField(max_length=15)),
                ('d_correo', models.CharField(max_length=100)),
                ('d_contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dietas_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField()),
                ('estatus', models.BooleanField(default=True)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dietas')),
            ],
            options={
                'db_table': 'dietas_usuarios',
            },
        ),
        migrations.CreateModel(
            name='miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Frecuente', 'Frecuente'), ('Ocasional', 'Ocasional'), ('Nuevo', 'Nuevo'), ('Esporádico', 'Esporádico'), ('Una sola visita', 'Una sola visita')], default='Frecuente', max_length=20)),
                ('membresia_activa', models.BooleanField(default=True)),
                ('antiguedad', models.CharField(max_length=80)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'miembros',
            },
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=60)),
                ('numero_empleado', models.IntegerField()),
                ('fecha_contratacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='preguntas_nutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas_x_dia', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5 o mas', '5 o mas')], default='2', max_length=20)),
                ('variedad_comidas', models.CharField(choices=[('Nunca', 'Nunca'), ('Algunas Veces', 'Algunas Veces'), ('Normalmente', 'Normalmente'), ('Siempre', 'Siempre')], default='Nunca', max_length=20)),
                ('regularidad_carbohidratos', models.CharField(choices=[('Nunca', 'Nunca'), ('Algunas Veces', 'Algunas Veces'), ('Normalmente', 'Normalmente'), ('Siempre', 'Siempre')], default='Nunca', max_length=20)),
                ('grasa_g', models.CharField(choices=[('10g', '10g'), ('30g', '30g'), ('60g', '60g'), ('100g o mas', '100g o mas')], default='10g', max_length=20)),
                ('calorias_consumidas', models.CharField(choices=[('Menos de 1000 Kcal', 'Menos de 1000 Kcal'), ('1000 Kcal', '1000 Kcal'), ('1500 Kcal', '1500 Kcal'), ('2000 Kcal', '2000 Kcal'), ('2500 Kcal', '2500 Kcal'), ('3000 Kcal', '3000 Kcal'), ('3500 Kcal', '3500 Kcal'), ('4000 Kcal', '4000 Kcal'), ('Mas de 4000 Kcal', 'Mas de 4000 Kcal')], default='Menos de 1000 Kcal', max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'preguntas_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='seguimientos_dietas_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estatus', models.CharField(choices=[('Programada', 'Programada'), ('Iniciada', 'Iniciada'), ('Seguimiento', 'Seguimiento'), ('Suspendida', 'Suspendida'), ('Finalizada', 'Finalizada')], default='Programada', max_length=20)),
                ('porcentaje_avance', models.CharField(choices=[('0% a 10%', '0% a 10%'), ('11% a 20%', '11% a 20%'), ('21% a 30%', '21% a 30%'), ('31% a 40%', '31% a 40%'), ('41% a 50% ', '41% a 50%'), ('51% a 60% ', '51% a 60%'), ('61% a 70% ', '61% a 70%'), ('71% a 80% ', '71% a 80%'), ('81% a 90% ', '81% a 90%'), ('91% a 100% ', '91% a 100%')], default='0% a 10%', max_length=20)),
                ('dieta_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dietas_usuarios')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
            options={
                'db_table': 'seguimientos_dietas_usuarios',
            },
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('total_clientes_atendidos', models.IntegerField()),
                ('promedio_clientes_x_dia', models.IntegerField()),
                ('capacidad_maximo', models.IntegerField()),
                ('total_empleados', models.IntegerField()),
                ('horario_disponibilidad', models.TextField()),
                ('estatus', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursales'),
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.BinaryField(max_length=256)),
                ('tipo', models.CharField(choices=[('Empleado', 'Empleado'), ('Vicitante', 'Vicitante'), ('Miembro', 'Miembro'), ('Instructor', 'Instructor')], default='Empleado', max_length=20)),
                ('estatus_conexion', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Banned', 'Banned')], default='Online', max_length=20)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=60)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='membresias_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_visita', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membresias')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'membresias_usuarios',
            },
        ),
        migrations.AddField(
            model_name='dietas_usuarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
        migrations.CreateModel(
            name='valoraciones_nutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('fecha_valoracion', models.DateTimeField(auto_now=True)),
                ('comentarios', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
                ('indicador_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicadores_nutricionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'valoraciones_nutricionales',
            },
        ),
    ]
